### ISSUE TITLE
Support reading from multiple partitions

### ISSUE THREAD

**Issue by mre** [mre/kafka-influxdb#10]
Kafka-Python has multiprocess support. We should use it for message consumption.

**Comment by aglagla** [comment]
@mre this would be awesome.
In particular, I'm interested in a configurable way to consume from
different topics and write to different influxdb databases. That would be a
tuple list in the yaml.

Regards,

Alexis

**Comment by mre** [comment]
@aglagla actually I only want to add support to read from multiple partitions for the same Kafka topic. This should improve performance quite a bit.

Nevertheless you can start more than one instance of kafka-influxdb to read from different Kafka topics and write to separate InfluxDB instances. This keeps the setup simple and it also helps to maintain a good overview of your current Kafka topics. This is also how logstash does it. 
 
Also see https://github.com/mre/kafka-influxdb/issues/5#issuecomment-147983565

**Comment by nhproject** [comment]
Hi,

Related to this issue - I'm experiencing big performance issues.

I'm using this flow:
CollectD --> Kafka --> InfluxDB --> Grafana
When I'm reaching 100 events per second, InfluxDB starts to consume the events in delay.
This delay is accumulated, so after a while the delay is severe (can reach hours of delay!)

Is there any estimation for this issue to be resolved?

Thanks,

Nitz

**Comment by mre** [comment]
@nhproject, thanks for the report. 100 events per second isn't a lot of traffic. I've benchmarked it with more than 10.000 messages/s - all from my local machine. So something is really fishy here. Can you run the kafka-influxdb benchmark in verbose mode? E.g.

    kafka_influxdb -c your_configfile.yml -b -v

Also maybe you could post your configfile so we can have a look.
Do you think this issue is related to the reading speed from Kafka? If not, then maybe we should move this conversation to another issue

**Comment by mre** [comment]
Actually multiple-partition handling is already part of kafka-python as well as pykafka so nothing to do here :smiley:
