### ISSUE TITLE
Activity seems low - is this an active project?

### ISSUE THREAD

**Issue by bradmallan** [mre/kafka-influxdb#102]
I like the premise and so do others judging by the forks but activity seems low?

Are there any performance benchmarks done? Even if informal?

**Comment by mre** [comment]
The project should work as expected, and bug fixes are very welcome but activity on new functionality is quite low, you're right. Maybe we should reflect that in the `README.md`.
I did some [performance benchmarks](https://github.com/mre/kafka-influxdb#performance) back then, which you probably saw already in the docs. Other than that I'm not aware of any benchmarks.

**Comment by mre** [comment]
If you're setting up a completely new pipeline, check out [vector](vector.dev/), which I'm migrating my stuff to. The community is quite welcoming to additions if things are missing.

**Comment by bradmallan** [comment]
vector link not working

**Comment by mre** [comment]
Hehe, sorry.
