### ISSUE TITLE
collectd_graphite_encoder reads only one measurement

### ISSUE THREAD

**Issue by rashshah** [mre/kafka-influxdb#12]
collectd_graphite_encoder,  when there are multiple measurements in kafka message,  it adds only one measurement in influxdb.   Seems like problem in for loop.  Is it known issue?

**Comment by mre** [comment]
@rashshah thanks for the report. I will have a look asap.

**Comment by mre** [comment]
@rashshah could you give me an example message that is not working for you? This would make debugging a lot easier for me ;-)

**Comment by mre** [comment]
I think I found the bug. Please check in master.

**Comment by rashshah** [comment]
Changes looks good and works ok. One suggestion, in exception instead of "Error in encoder", say "empty line". Every message from kafka has the empty line in end, and this message will become annoying. Alternatively add check : "if line "

Pls release next version.

Regards,

rashmikant

**Comment by mre** [comment]
New version 0.7.2 is out now. :-)

**Comment by rashshah** [comment]
Thanks.

What is kafka-influxdb tightly coupled with requests=2.8.0?   I have some other python packages,  which uses 2.8.1,  then kafka-influxdb throws error.

Traceback (most recent call last):
  File "/usr/local/bin/kafka_influxdb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3057, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 641, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 654, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 827, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.8.0' distribution was not found and is required by kafka-influxdb

**Comment by mre** [comment]
@rashshah you're right. That shouldn't be the case. What I will do is follow the guideline on http://stackoverflow.com/a/7085000/270334. Will create a ticket for that. Thanks for the hint.

**Comment by mre** [comment]
@rashshah this should be fixed in master now. Would be glad for any feedback.
