### ISSUE TITLE
Exception when running kafka-influxdb

### ISSUE THREAD

**Issue by pwnmagic** [mre/kafka-influxdb#3]
**Issue**
* Writes to influxdb fail. I find no information when I query influxdb.
* Running into exceptions when using kafka-influxdb (see log excerpts below).

**Log Excerpt**
    Exception caught while flushing: write_points_with_precision() takes at most 3 arguments (5 given)
    Flush 17. Buffer size 1000. Parsed 17000 kafka mes. into 17000 datapoints. Speed: 10077 kafka mes./sec
    Exception caught while flushing: write_points_with_precision() takes at most 3 arguments (5 given)
    Flush 18. Buffer size 1000. Parsed 18000 kafka mes. into 18000 datapoints. Speed: 10095 kafka mes./sec
    Exception caught while flushing: write_points_with_precision() takes at most 3 arguments (5 given)
   Flush 19. Buffer size 1000. Parsed 19000 kafka mes. into 19000 datapoints. Speed: 10144 kafka mes./sec
    Exception caught while flushing: write_points_with_precision() takes at most 3 arguments (5 given)
    Flush 20. Buffer size 1000. Parsed 20000 kafka mes. into 20000 datapoints. Speed: 10209 kafka mes./sec

**Code Reference**
https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb.py#L119

**Producer**
Using kafka-influxdb, I am consuming from kafka topic written by the [collectd write_kafka](https://github.com/collectd/collectd/blob/master/src/write_kafka.c) plugin.

**More Info**
I get an exception about write_points_with_precision() (which is
[deprecated](https://github.com/influxdb/influxdb-python/blob/master/influxdb/influxdb08/dataframe_client.py#L66-L76) and I noticed that you are using write_points so not sure where the issue is yet. Will have to dig through the code further to see what I am missing. Let me know if any other info is required.

**Comment by pwnmagic** [comment]
This issue is because of the data format that was set (json) for collectd write_kafka plugin.

**Comment by mre** [comment]
Thanks for the detailed report. I will try to reproduce the issue when I find the time. Could you tell me which version of InfluxDB you're running and the version of your influxdb python client?

**Comment by pwnmagic** [comment]
InfluxDB: 0.8.8-1 on CentOS 6.6
Python: 2.7

I think handling collectd json format would help resolve this issue. I can work on it when I get some free time.

**Comment by mre** [comment]
Thanks @pwnmagic. Yes you're right. I was thinking about a general solution to handle all json formats. But I think right now supporting the collectd-kafka plugin would be nice.

**Comment by mre** [comment]
@pwnmagic I've released a big update today which supports InfluxDB 0.9.1. Maybe you have the time to test this and report back. I would really appreciate your input. :-)

**Comment by pwnmagic** [comment]
Sweett!! I was planning to work on this next weekend ;)

I'll get back to you once I test it out.

-Tarun

**Comment by mre** [comment]
@pwnmagic any update on this? Otherwise I would close the issue.

**Comment by pwnmagic** [comment]
Sorry @mre, haven't gotten a chance to test this out. Won't be able to work on this in the next few weeks as well. Closing this for now.
