### ISSUE TITLE
[Question] PyPy compatibility?

### ISSUE THREAD

**Issue by bluebob** [mre/kafka-influxdb#31]
Anyone know if kafka-influxdb is compatible with PyPy?
I was doing a load test the other day and was seeing 30-35% cpu use (single cpu VM), so I'm thinking that if PyPy was supported then that might give me some "better" performance under heavy load.

**Comment by mre** [comment]
Yes it should work with PyPy. We mention it quickly here: https://github.com/mre/kafka-influxdb#benchmark. It should be 3-5 times as fast. Please report back. :wink: 

That said, there's some issues we might need to resolve(#30, #29). Maybe you could also have a look and see if you can help?

**Comment by mre** [comment]
Closing this. Feel free to reopen for further questions.
