### ISSUE TITLE
pip install kafka_influxdb on CentOS7 failed

### ISSUE THREAD

**Issue by meetpradeepp** [mre/kafka-influxdb#32]
I tried installing kafka-influxdb using pip it failed. But when I ran the same thing by downloading the code and using python setup.py install it worked.

[root@centos-agent ~]# pip install kafka_influxdb
Collecting kafka_influxdb
  Downloading kafka_influxdb-0.7.2.tar.gz
Collecting certifi==2015.9.6.2 (from kafka_influxdb)
  Downloading certifi-2015.9.6.2-py2.py3-none-any.whl (371kB)
    100% |████████████████████████████████| 378kB 184kB/s
Collecting funcsigs==0.4 (from kafka_influxdb)
  Downloading funcsigs-0.4-py2.py3-none-any.whl
Collecting influxdb==2.9.2 (from kafka_influxdb)
  Downloading influxdb-2.9.2-py2.py3-none-any.whl (256kB)
    100% |████████████████████████████████| 266kB 259kB/s
Collecting kafka-python==0.9.4 (from kafka_influxdb)
  Downloading kafka-python-0.9.4.tar.gz (63kB)
    100% |████████████████████████████████| 71kB 47kB/s
Collecting mock==1.3.0 (from kafka_influxdb)
  Downloading mock-1.3.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 162kB/s
Collecting nose==1.3.7 (from kafka_influxdb)
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 88kB/s
Collecting pbr==1.8.0 (from kafka_influxdb)
  Downloading pbr-1.8.0-py2.py3-none-any.whl (87kB)
    100% |████████████████████████████████| 92kB 132kB/s
Collecting python-dateutil==2.4.2 (from kafka_influxdb)
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 70kB/s
Collecting pytz==2015.6 (from kafka_influxdb)
  Downloading pytz-2015.6-py2.py3-none-any.whl (475kB)
    100% |████████████████████████████████| 481kB 61kB/s
Collecting PyYAML==3.11 (from kafka_influxdb)
  Downloading PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 64kB/s
Collecting requests==2.8.0 (from kafka_influxdb)
  Downloading requests-2.8.0-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 481kB 61kB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from kafka_influxdb)
Collecting virtualenv==13.1.2 (from kafka_influxdb)
  Downloading virtualenv-13.1.2-py2.py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 63kB/s
Collecting wheel==0.24.0 (from kafka_influxdb)
  Downloading wheel-0.24.0-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 105kB/s
Building wheels for collected packages: kafka-influxdb, kafka-python, PyYAML
  Running setup.py bdist_wheel for kafka-influxdb ... done
  Stored in directory: /root/.cache/pip/wheels/d0/ab/21/e55a9338b9fd3809c5e919d9763edc60225c08e5e0a41c2351
  Running setup.py bdist_wheel for kafka-python ... done
  Stored in directory: /root/.cache/pip/wheels/1f/13/49/c9e3e163f95d492cd2835a975b0733b98a943dbad800621d13
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/4a/bf/14/d79994d19a59d4f73efdafb8682961f582d45ed6b459420346
Successfully built kafka-influxdb kafka-python PyYAML
Installing collected packages: certifi, funcsigs, requests, pytz, python-dateutil, influxdb, kafka-python, pbr, mock, nose, PyYAML, virtualenv, wheel, kafka-influxdb
  Found existing installation: wheel 0.29.0
    Uninstalling wheel-0.29.0:
      Successfully uninstalled wheel-0.29.0
Successfully installed PyYAML-3.11 certifi-2015.9.6.2 funcsigs-0.4 influxdb-2.9.2 kafka-influxdb-0.7.2 kafka-python-0.9.4 mock-1.3.0 nose-1.3.7 pbr-1.8.0 python-dateutil-2.4.2 pytz-2015.6 requests-2.8.0 virtualenv-13.1.2 wheel-0.24.0

[root@centos-agent kafka_influxdb]# kafka_influxdb -c kafka_influxdb_conf.yaml
Reading config file kafka_influxdb_conf.yaml
Traceback (most recent call last):
  File "/usr/bin/kafka_influxdb", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/kafka_influxdb.py", line 102, in main
    start_consumer(config)
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/kafka_influxdb.py", line 118, in start_consumer
    encoder = load_encoder(config.encoder)
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/encoder/__init__.py", line 9, in load_encoder
    encoder_module = importlib.import_module(modname)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named kafka_influxdb.encoder.collectd_graphite_encoder

**Comment by mre** [comment]
Hi @meetpradeepp. Thanks for your feedback.
you could try the idea from #30. Please report back if it works for you.

**Comment by meetpradeepp** [comment]
Hello @mre. Thank for your quick response. Yes changing the encoder name in config.yaml from "kafka_influxdb.encoder.collectd_graphite_encoder" to "collectd_graphite_encoder" works. 

I reconfirmed that if you install python setup.py install the encoder with "kafka_influxdb.encoder.collectd_graphite_encoder" name works. Looks like this happens because kafka_influxdb/encoder/collectd_graphite_encoder is the location of actual code with respect to setup.py.

**Comment by mre** [comment]
Thanks for your feedback @meetpradeepp. :-) Closing.
