### ISSUE TITLE
Test new versions of Kafka libraries

### ISSUE THREAD

**Issue by mre** [mre/kafka-influxdb#34]
https://github.com/confluentinc/confluent-kafka-python
https://pypi.python.org/pypi/kafka-python
https://github.com/Parsely/pykafka

Found in this nice blog post: http://blog.parsely.com/post/3886/pykafka-now/

**Comment by mre** [comment]
Another benchmark. The confluent kafka client is in front: http://activisiongamescience.github.io/2016/06/15/Kafka-Client-Benchmarking/

**Comment by aglagla** [comment]
I was just going to report an issue with kafka 0.10 and influxdb 0.13.
Also, I am using confluent python client as a producer and I am pretty much impressed by the performance, there fore considering using it in the writer/reader kafka_influxdb implementation.
My issue with kafka 0.10 is that I cannot consume a very simple batch of 10 messages, each containing a well-formatted Line Protocol text with timestamps. I am using the echo_encoder encoder.  For very small chunks of messages, kafka_influxdb just seem to ignore them.
For very large sets of messages, it's reading the payloads character by character (I have verified that payloads were OK with the standard kafka simple-consumer).

I can provide more details if needed.

Thanks,

Alexis

**Comment by mre** [comment]
Did some preliminary benchmarks for the two most promising candidates, pykafka and confluent-kafka-python.
Tested both together with librdkafka support on a high-performance topic with 10 partitions.
Here's the results:
confluent-kafka-python: around 300.000msg/s
pykafka+rdkafka: around 100.000 msg/s

My only issue with confluent-kafka-python is that it doesn't support Zookeeper, so Kafka 0.8.x support is not the best. I was thinking of a workaround to manually assign partitions on startup.

So, instead of writing:
```python
c = Consumer(**conf)
c.subscribe(['metrics'])
```

I would write

```python
c = Consumer(**conf)
c.assign([TopicPartition('metrics', p) for p in range(1,11)])
```

(Note: I've hardcoded the number of partitions here because I haven't found a way to read that information with confluent-kafka-python)

The disadvantage would be that the consumer would stop working after broker reassignment (I guess).
But it's a workaround that would only be required for Kafka 0.8.x anyway so I'm willing to take this route as a trade-off for the high performance.

**Comment by mre** [comment]
@aglagla I've pushed a big update to master today. It contains the confluent-kafka consumer. Would be great if you could give it a try. It should be much more performant, robust and flexible. :smiley:

**Comment by edenhill** [comment]
Just thought I'd commen on this:
> The disadvantage would be that the consumer would stop working after broker reassignment (I guess).

The client (librdkafka) will automatically switch to the new partition leader on failover, the application wont have to do anything (and might not even notice), so your assign() proposal will work good.


This might be somewhat off-topic, but looking at your performance test charts (which are great!) I see the huge difference between optimized `-O` runs and non-optimized runs for the confluent client.
So I looked into what `-O` actually does in Python, and it isn't much: disabling docstrings, asserts and __debug__, that's about it. And that probably only applies to compiled Python code, not prebuilt CPython extensions as is the case with confluent-kafka-python, which makes me wonder why there is such a big difference between the runs.

I tried to find the performance test code used but couldn't find it.
Could you shed some light on how these tests are performed and how&where thruput rates are measured?
Thanks

**Comment by mre** [comment]
Hey @edenhill. Thanks for commenting. Huge fan of your work!
We use librdkafka heavily at trivago. We pump all our monitoring and logging data through it and we're very happy with the performance and reliability.

Glad to hear that the manual assignment will work on failover as well. :smiley:
One thing I couldn't find out is how to get the number of partitions from a topic with confluent-kafka-python. Is there a way?

About the performance tests: I was also surprised.
The benchmark code is not in the repo, but here's the gist:
https://gist.github.com/mre/5509edfa576fd4a0a8df13849b72fe51
(As you can see, no magic here. :wink:)
Please not that  I read from ten partitions here.

In a quick test I get 266.255 messages/s right now, but this value varies depending on the time of day. In the evening I reach even better performance.

In case of the benchmark, `-O` doesn't make any difference.
It does make a difference when running it inside `kafka-influxdb`, though.
I am completely disabling the debug logging with that:
https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/reader/confluent.py#L61
The interpreter is smart enough to remove the bytecode for logging in this case which avoid copying and serializing messages to stdio, I guess.
I was able to get a nice performance boost because of that.
