### ISSUE TITLE
Unexpected behaviour with influxdb 0.13

### ISSUE THREAD

**Issue by aglagla** [mre/kafka-influxdb#35]
To reproduce, set up an influxdb 0.13 server and run kafka_influxdb in benchmark mode.
kafka-influxdb output:

```
WARNING:root:Cannot write data points: 400: {"error":"unable to parse '2': missing fields\nunable to parse '6': missing fields\nunable to parse 'f': missing fields\nunable to parse '2': missing fields\nunable to parse 'f': missing fields\nunable to parse 'c': missing fields\nunable to parse '9': missing fields\nunable to parse '1': missing fields\nunable to parse '8': missing fields\nunable to parse 'f': missing fields\nunable to parse '5': missing fields\nunable to parse '0': missing fields\nunable to parse '.': missing fields\nunable to parse 'l': missing fields\nunable to parse 'o': missing fields\nunable to parse 'a': missing fields\nunable to parse 'd': missing fields\nunable to parse '.': missing fields\nunable to parse 'l': missing fields\nunable to parse 'o': missing fields\nunable to parse 'a': missing fields\nunable to parse 'd': missing fields\nunable to parse '.': missing fields\nunable to parse 's': missing fields\nunable to parse 'h': missing fields\nunable to parse 'o': missing fields\nunable to parse 'r': missing fields\nunable to parse 't': missing fields\nunable to parse 't': missing fields\nunable to parse 'e': missing fields\nunable to parse 'r': missing fields\nunable to parse 'm': missing fields\nunable to parse '0': missing fields\nunable to parse '.': missing fields\nunable to parse '0': missing fields\nunable to parse '5': missing fields\nunable to parse '1': missing fields\nunable to parse '4': missing fields\nunable to parse '3': missing fields\nunable to parse '6': missing fields\nunable to parse '3': missing fields\nunable to parse '5': missing fields\nunable to parse '7': missing fields\nunable to parse '6': missing fields\nunable to parse '3': missing fields\nunable to parse '0': missing fields"}
```

Influxdb log excerpt:

```

2
6
f
2
f
c
9
1
8
f
5
0
.
l
o
a
d
.
l
o
a
d
.
l
o
n
g
t
e
r
m

0
.
0
5

1
4
3
6
3
5
7
6
3
0
...
```

kafka-simple-consumer:

```
26f2fc918f50.load.load.shortterm 0.05 1436357630
            26f2fc918f50.load.load.midterm 0.05 1436357630
            26f2fc918f50.load.load.longterm 0.05 1436357630
```

Note: upgraded the python influxdb client (3.0.0), same issue.

Greetings,

Alexis

**Comment by mre** [comment]
Thanks for the thorough issue description. I'm gonna have a look whenever I find some time. Due to being busy with other projects I'm not sure when that will be, so help is definitely wanted.
If anybody would like to have a go at this and create a pull request, I'd be more than happy to review it.

**Comment by aglagla** [comment]
Hi @mre ,

I've forked your repo in order to experiment with the confluent python api (and librdkafka).
adding an "api" parameter and fixing the issue with the writer.

As this is experimental, have not submitted a pull request, since there are several issues to check still.

For instance, I need to perform more tests with the consumer group offset in different scenarios for failover. I can only say that it's extremely fast.
The issue with the line split seen above is in the worker, where the buffer is joined with "\n".
As my case has one line per message, which included a trailing "\n" already, my solution was to add a rstrip("\n") on the writer. But that might just be my data.

Fork here : https://github.com/aglagla/kafka-influxdb

Rgds,

Alexis

**Comment by mre** [comment]
I've had a look and I really like what I see. There's a lot of nice improvements.
Maybe the ConfluentKafkaReader could be moved to a separate file and the read method (https://github.com/aglagla/kafka-influxdb/blob/master/kafka_influxdb/reader/kafka_reader.py#L41) might need some refactoring to make it a bit more testable.
Apart from that I'd merge it as soon as you finished your tests. :+1:

**Comment by aglagla** [comment]
Hi @mre ,

Sorry for the delay. Yes. I agree on the refactoring/testing, should be straightforward.

Greetings,

Alexis

**Comment by aglagla** [comment]
Hi @mre 
I've split the code as suggested.
While checking your unit tests, I'm surprised to see mocking at both sides of the tests.
Hence I've just added the original Confluent's Consumer unit test code.

Regards,

Alexis

**Comment by mre** [comment]
Cool! Thanks for that @aglagla. 
You did a great job in contributing to this project so far. I hope you keep it up.
You now have full commit rights to this repo now, so you can merge your changes whenever you like. :smiley:

**Comment by kaffeiflex** [comment]
Hi aglagla,


Would you please provide your sample data?

Is this "26f2fc918f50.load.load.shortterm 0.05 1436357630" the final data format when writing to influxdb? If so, the error message has described the reason: there is no fields. It should be "26f2fc918f50.load.load.shortterm value=0.05 1436357630". 

Also, character "." is not supporting for measurement name when you do querying.

**Comment by mre** [comment]
Pushed some changes to master. Tested against InfluxDB 1.0 and your test data should work now.
Please test again.

**Comment by mre** [comment]
There has not been any feedback regarding this issue, so I assume it is resolved or no longer relevant. Please reopen if necessary.
