### ISSUE TITLE
Integrating kafka influxdb with my own collector and kafka environment

### ISSUE THREAD

**Issue by Trace810** [mre/kafka-influxdb#38]
I have my own collector that sends data to Kafka on an environment and I want to integrate Kafka-InfluxDB with it. I just want to verify the usage of Kafka-InfluxDB. 
I have created the config_example.yaml file and set the parameters there to point to my Kafka environment. Although, I am not sure what I should put in the encoder field. 
In order to consume the data from Kafka and push it into InfluxDB, do I just need to run this command ? - kafka_influxdb -c config-example.yaml

I am asking since I am aware that there is a Docker container that runs collectD, kakfa, kafka-influxDB and influxDB together. However I don't need this as I already have my own collector on a separate environment.

**Comment by mre** [comment]
Hi @Trace810,

the Docker setup is used for the integration tests.
Of course you can also run kafka-influxdb directly as you said. :smiley:

**Comment by Trace810** [comment]
Alright, thanks for verifying that! :)
