### ISSUE TITLE
Warnings and Errors on running kafka-influxdb

### ISSUE THREAD

**Issue by Trace810** [mre/kafka-influxdb#39]
Hi there. I am new to Kafka and I'm trying to use kafka-influxdb to store data coming in from my kafka environment. This is my config-example.yaml file

kafka:
  host: "kafka_environment.net"
  port: 9092
  topic: "topicname"
  group: "kafka-influxdb"
influxdb:
  host: "influxdb"
  port: 8086
  user: "root"
  password: "root"
  dbname: "mydb"
  use_ssl: false
  verify_ssl: False
  timeout: 5
  use_udp: False
  retention_policy: "default"
  time_precision: "s"

encoder: "collectd_json_encoder"
benchmark: false
buffer_size: 1000
statistics: true

 When I try to run it, I get the following error:

Traceback (most recent call last):
  File "/usr/bin/kafka_influxdb", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/kafka_influxdb.py", line 102, in main
    start_consumer(config)
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/kafka_influxdb.py", line 138, in start_consumer
    client.consume()
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/kafka_influxdb.py", line 35, in consume
    self.buffer.extend(self.encoder.encode(raw_message))
  File "/usr/lib/python2.7/site-packages/kafka_influxdb/encoder/collectd_json_encoder.py", line 27, in encode
    raise NotImplemented
TypeError: exceptions must be old-style classes or derived from BaseException, not NotImplementedType

I would really appreciate some input toward the right direction regarding this issue. 
Thanks.

**Comment by mre** [comment]
Hi @Trace810. Sorry for the late reply. The error probably points to using an old version of kafka-influxdb. In the [version on pypi](https://pypi.python.org/pypi/kafka_influxdb/0.7.2) (currently 0.7.2), the json encoder was not implemented. This is done on master but not released.
What you could do is cloning the project from github directly and trying again.
I hope to release 0.8 soon, though - including a new pip package. Don't hold your breath, though. :wink:

**Comment by mre** [comment]
Had some more time and pushed a new version (0.7.3) to pypi.
So if you are still interested in getting this running, please try it.  
Same installation as before:

```
pip install kafka_influxdb  
kafka_influxdb -c config-example.yaml
```

Cheers. :cocktail:

**Comment by Trace810** [comment]
@mre Thanks a lot! :)
