### ISSUE TITLE
Performance for write to influxDB with kafka connector

### ISSUE THREAD

**Issue by amoussoubaruch** [mre/kafka-influxdb#50]
Hi,

I started use kafka connector to write streaming data to influxDB. So i dispose one single node influxdb and when connector start all message start write to influxdb. And any queries i execute crash because i have more data. 

In kafka connector, is exit a paramater to configure for limit number of message comming from kafka so number of insert to my database. 

Thanks for advanced

**Comment by mre** [comment]
Hi @amoussoubaruch,

no there  is no parameter to limit the number of messages. I'm sorry but that's a bit outside of the scope of the project.

Some ideas:
* Can you limit the number of incoming messages from Kafka?
* How many messages do you send per second and what is the size of each message?
* What hardware are you using for InfluxDB? Maybe you can add more RAM or a faster CPU.

Also try to limit the number of results of your queries by setting a limit, e.g.
```> SHOW SERIES ON NOAA_water_database FROM "h2o_quality" WHERE "location" = 'coyote_creek' LIMIT 2```
(see the [documentation](https://docs.influxdata.com/influxdb/v1.2/query_language/schema_exploration/#examples-3))
