### ISSUE TITLE
ERROR:root:Error while creating InfluxDB datbase: database already exists

### ISSUE THREAD

**Issue by bennco1** [mre/kafka-influxdb#51]
Hello - I'm a huge fan of kafka-influxdb. I believe is solves a major issue when dealing with volumes of metrics traffic. Thank you!

I did notice one issue after deploying though, if I creat the influxdb database prior to sending the metrics I received the following error "ERROR:root:Error while creating InfluxDB datbase: database already exists". 

I'm able to avoid the error by having the DB created by kafka-influxdb. This creates a concern because if I have an outage which interrupts kafka-influxdb connection then I am unable to continue writing to my existing database. 

What's the recommended way to run kafka-influxdb? I have multiple kafka nodes and attempted to execute the kafka-influxdb consumer on each node but realize they cannot produce to the same database. Any recommendations to configure this with some resiliency?

**Comment by mre** [comment]
Oh wow. Don't know how I could miss that. Sorry. 😦
After #52 is merged it should be fine.

**Comment by mre** [comment]
Should be fixed now. Can you give it another try?
If you installed with pip, run this:

```
pip install --upgrade kafka_influxdb
```

If you cloned from git you can pull it from the master.

```
git pull origin master
```

Cheers. 🍸

**Comment by bennco1** [comment]
Thanks for the update no sorry needed, I appreciate the work. I did an upgrade and now I am getting the following error...

raceback (most recent call last):
  File "/usr/local/bin/kafka_influxdb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'kafka-influxdb==0.9.0' distribution was not found and is required by the application

**Comment by mre** [comment]
Hm... that looks strange. What commands did you use?

**Comment by bennco1** [comment]
I did pip install --upgrade kafka_influxdb - once completed I ran the following kafka_influxdb --help then go the errors above then I tried running the configuration with kafka_influxdb -c kafka-influxdb.yml same errors.

**Comment by bennco1** [comment]
disregard the above - found my error - the new code working like a charm!!!! Thanks man. Now is it possible to reduce the amount of load pushed to influx? I'm currently using the following parameter within my yml file buffer_size: 500 but I'm not sure if it's being evoked.

**Comment by bennco1** [comment]
also while I saw this message via stdou, Im not sure if it's due to recent change but haven't seen it before. 

WARNING:root:Cannot write data points: {"error":"error fetching meta data: no leader detected during fetchMetaData"}

**Comment by mre** [comment]
Okay, so we've made some progress.
As for throttling messages, there was a similar request before (#50). You could add a comment to that. Maybe we can reopen this ticket if you like. 

About the warning message: that's okay as along as you don't get that regularly. It might happen that there was a Kafka leader election while trying to receive data. Usually such things even out after some time.

**Comment by bennco1** [comment]
Thanks man definitely will do.
