### ISSUE TITLE
Can this project loose data?

### ISSUE THREAD

**Issue by Armagedoom** [mre/kafka-influxdb#57]
After viewing the code, I don't see whether the project is protecting the user from data loss or not.
Specifically, If the reader reads a message from a Kafka topic, and cant deliver to InfluxDB because it is down, in the (rare) event that the process dies, we will loose that information too.
Right?

Thank you very much for this project!

**Comment by mre** [comment]
Yes.

[Here's the write loop](https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/worker.py#L88-L96). As you can see, the buffer is cleared whether we can write or not.
The reasoning behind this is, that metrics are ephermeral in kafka-influxdb and that Kafka acts as a buffer for metrics.

I see multipe options to change the behaviour:
1. We could add a config option to avoid clearing the buffer in case of failed writes. Bascically an if-condition around `self.buffer = []`.
2. Another option would be to add a [simple retry-loop like the one for creating the db](https://github.com/mre/kafka-influxdb/blob/efb59bc690b6633dbf3f9a2e3f375807b422504c/kafka_influxdb/worker.py#L74-L77).
3. Finally, we could combine 1 and 2 and drop the metrics after a predefined number of retries.
 
Don't know if I will ever get around to add one of these options, but maybe you want to try and create a pull request?

**Comment by Armagedoom** [comment]
Thank you  @mre.

Yes, we are considering to use this module for the solution we are developing, and if we end up using it, you can count on the pull requests.

Also, the plan is to use it as ground to create a Kafka-Elasticsearch consumer too.

But what I don't understand yet is, even if we develop solution 1 and 2, we still wouldn't be safe against an eventual process shutdown, would we?

Specifically, when is the module sending a feedback to Kafka in order to confirm that the message read has been delivered, so Kafka "knows" which messages were delivered and which weren't?

We have a [reader.read()](https://github.com/mre/kafka-influxdb/blob/aeb9be820c51fb514f97cc993d15811109a964cd/kafka_influxdb/worker.py#L43) getting the message, but Its delivery is never confirmed.

Quoting [Confluent blog](https://www.confluent.io/blog/introduction-to-apache-kafka-for-python-programmers/) for the parameter `enable.auto.commit`:

> Often you would like more control over exactly when offsets are committed. In this case you can set enable.auto.commit to False and call the commit method on the consumer.

**Comment by mre** [comment]
> But what I don't understand yet is, even if we develop solution 1 and 2, we still wouldn't be safe against an eventual process shutdown, would we?

That's correct. If the process gets shut-down, the metrics in the buffer get lost.
One could manually commit the offset and have a handler flush the remaining metrics on shutdown to avoid this. On the other side, this would move some of the offset logic from the server (Kafka) to the client (kafka-influxdb).
It's a tradeoff between code complexity and robustness.

Is the data you're trying to pipe to InfluxDB mission critical?

**Comment by Armagedoom** [comment]
I'm going to work a bit more on it and keep you posted.
Looks like just by setting the consumer `enable.auto.commit` to False and doing commits ourselves whenever we flush, we would have this module granting the delivery.

**Comment by Armagedoom** [comment]
(I answered again while you had already answered, my bad).
Yes, the data is critical, we shouldn't loose metrics.

**Comment by mre** [comment]
Guaranteed delivery is a hard problem. `kafka-influxdb` is currently optimized for raw performance and "realtime capabilities". Your help is much appreciated in improving its robustness, but just to be 100% transparent here, let me mention some competing projects:
* [gollum](https://github.com/trivago/gollum) is trivago's log consumer, which handles some of our more business-critical data.
* [telegraf](https://github.com/influxdata/telegraf) is InfluxDB's monitoring daemon, which can also be used to create a Kafka-to-InfluxDB pipeline. (See [here](https://github.com/mre/kafka-influxdb/tree/master/docker/telegraf)).
* [logstash](https://www.elastic.co/de/products/logstash) is a candidate from Elastic.

Might be worth comparing all solutions and test their reliability guarantees. 😉

**Comment by Armagedoom** [comment]
Big thanks for the clarity and your suggestions, ended up using logstash because it was very straightforward to integrate with Elasticsearch too, plus there are ways to grant exactly once delivery.
Thanks again!
