### ISSUE TITLE
DEBUG:root:None?

### ISSUE THREAD

**Issue by mimmus** [mre/kafka-influxdb#58]
I started an InfluxDB using Docker as described at:
https://hub.docker.com/_/influxdb/
but I'm unable to load anything from a Kafka topic "connect-test".
This is the verbose output:

```
# kafka_influxdb -vvv  -c config.yaml
Reading config file config.yaml
DEBUG:root:Initializing Kafka Consumer
DEBUG:root:Initializing connection to InfluxDB at localhost:8086
INFO:root:Connecting to InfluxDB at localhost:8086 (SSL: False, UDP: False)
DEBUG:root:Initializing message encoder: kafka_influxdb.encoder.collectd_graphite_encoder
INFO:root:Creating InfluxDB database if not exists: metrics
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8086 "GET /query?q=CREATE+DATABASE+%22metrics%22&db=metrics HTTP/1.1" 200 None
INFO:root:Listening for messages on Kafka topic connect-test...
INFO:root:Connecting to Kafka with the following settings:
 {'default.topic.config': {'auto.offset.reset': 'largest'}, 'bootstrap.servers': 'localhost:9092', 'offset.store.method': 'broker', 'group.id': 'kafka-influxdb'}...
DEBUG:root:<cimpl.Message object at 0x2268210>
INFO:root:connect-test [0] reached end at offset 524608 with key None

DEBUG:root:None
DEBUG:root:None
DEBUG:root:None
DEBUG:root:None
...
```
Database is created but then I have only "DEBUG:root:None" message endlessly.
I tried also to reset offsets of my Kafka topic but no results.
Any help?

**Comment by mre** [comment]
Hello @mimmus,

it says "reached end at offset ...", so maybe you can try sending a new message to the `connect-test` topic?

**Comment by mimmus** [comment]
I'm in a development cycle: can I reset offset and restart from scratch?

**Comment by mre** [comment]
That's not supported right now. It's hardcoded as you can [see here](https://github.com/mre/kafka-influxdb/blob/16c1df42fb05d994722a0a0f273a9c957c725115/kafka_influxdb/reader/confluent.py#L37). That said, I could try to refactor that to make it configurable. Give me a few minutes and I'll see what I can do.

**Comment by mre** [comment]
@mimmus can you have a look at the changes linked above?

**Comment by mre** [comment]
If you want to try it locally, you would have to do something like the following (warning: writing this from the top of my head):

```
git clone git@github.com:mre/kafka-influxdb.git
cd kafka-influxdb
git checkout kafka-offset-config
pip install -r requirements.txt
# Copy over your `config.yaml`
python -m kafka_influxdb -vvv  -c config.yaml --kafka_offset smallest
```

**Comment by mimmus** [comment]
Trying just now...

**Comment by mimmus** [comment]
It works, thank you very much.
I'm not a Kafka guru but loading a bunch of data in InflusxDB using your tool was really simple.
