### ISSUE TITLE
there isnt a docker image for this project

### ISSUE THREAD

**Issue by mrafeeq** [mre/kafka-influxdb#62]
Can you create a stable public docker image for this project please. there isn't one, that seems to be maintained at this moment .

This is not an bug/issue but a request to create and publish a docker image

**Comment by mre** [comment]
Sure. I've updated the `README.md` and added a simple Docker image.
Please check it out and tell me if I missed anything. 😃

**Comment by mrafeeq** [comment]
Why not push the image to docker hub also the docker has dependency on kafka and influx, in commercial projects,  these images may be  run in different containers why is there a dependency , how to run without the dependency

**Comment by mrafeeq** [comment]
I havce one more question messages that are published to a kafka topic are in json format, are there any message transformers available so that we an transform it into a format that influx expects

**Comment by mre** [comment]
But... it IS on Dockerhub: https://hub.docker.com/r/mre0/kafka-influxdb/ Or maybe I don't get your question? 😅
Also, what do you mean by "dependency to Kafka and InfluxDB"? It uses the Python modules to communicate with those (after all, the project is called kafka-influxdb :wink:), but Kafka and InfluxDB themselves are not part of the Docker image.

You can write a custom encoder to support any input and output format (even fancy things like Protobuf). Look at the examples inside the encoder directory to get started. The following formats are officially supported: https://github.com/mre/kafka-influxdb#supported-formats

**Comment by mrafeeq** [comment]
I am passing a message like `somemeasure,somekey=somevalue fromState=Responding,toState=Available`

to the topic  i get the error 

> DEBUG:root:Error in encoder: not enough values to unpack (expected 3, got 2)
> DEBUG:root:<cimpl.Message object at 0x1101c9228>
> INFO:root:test [0] reached end at offset 22 with key None
