### ISSUE TITLE
Official image on docker hub

### ISSUE THREAD

**Issue by teone** [mre/kafka-influxdb#68]
Is there an official image on dockerhub for this tool?

**Comment by mre** [comment]
Hi @teone,
does the image mentioned in the docs work for you?
https://github.com/mre/kafka-influxdb#docker

**Comment by teone** [comment]
Oh sorry,
I missed it.

Is there a recommended way to load a custom encoder in that image or is it better to rebuild it from code?

**Comment by mre** [comment]
That came up recently: https://github.com/mre/kafka-influxdb/issues/65
If it works, could you create a pull request to add this information to the readme? 😊

**Comment by mre** [comment]
You know, the boyscout rule. 😉

**Comment by teone** [comment]
There you go! https://github.com/mre/kafka-influxdb/pull/69
I also added a simple example to create a custom image that wraps the custom encoder (that's the solution I found) as I think it may be more manageable across different environments (KB8s, Swarm, docker-compose) or if you want to share that same image with teammates.

By the way thanks for the tool!

**Comment by mre** [comment]
Thanks! Closed via #69.
