### ISSUE TITLE
Add SSL params

### ISSUE THREAD

**Issue by panda87** [mre/kafka-influxdb#7]
Please add the following paras to the implementation and to the config file:
ssl (bool) – use https instead of http to connect to InfluxDB, defaults to False
verify_ssl (bool) – verify SSL certificates for HTTPS requests, defaults to False

Thanks a lot!
D.

**Comment by mre** [comment]
Just pushed the necessary changes.
https://github.com/mre/kafka-influxdb/commit/f0b52b5556ca0e69b361d6515a79fae8f30d82e8
It would be great if you could check it out and report back.

**Comment by panda87** [comment]
Thanks! i'll check it

**Comment by panda87** [comment]
Looks good @mre 
Im closing the issue
