### ISSUE TITLE
Database created successfully, but with no measurements or content.

### ISSUE THREAD

**Issue by ShawnTheCoder** [mre/kafka-influxdb#70]
Hi,

I'm trying to build up a CollectD-Kafka-InfluxDB-Grafana setup.
With collectd-5.8.0, kafka-2.11-1.1.0, influxdb-1.6.0, and grafana-5.2.2-1, and today's master branch of kafka-influxdb on a CentOS 7.

I have successfully installed this kafka-influxdb with "pip install kafka_influxdb", and config file modified as below:

---
kafka:
  host: "localhost"
  port: 9092
  topic: "collectd"
  group: "my_group"
  reader: "kafka_influxdb.reader.confluent"
  #reader: "kafka_influxdb.reader.kafka_python" # Legacy consumer
influxdb:
  host: "localhost"
  port: 8086
  user: "root"
  password: "root"
  dbname: "collectd"
  use_ssl: false
  verify_ssl: False
  timeout: 5
  use_udp: False
  retention_policy: "autogen"
  time_precision: "s"
encoder: "kafka_influxdb.encoder.collectd_graphite_encoder"
buffer_size: 1000
statistics: true

When I run "kafka_influxdb -c config_example.yaml -v", the outputs are

[root@master kafka-influxdb-master]# kafka_influxdb -c config_example.yaml -v
Reading config file config_example.yaml
INFO:root:Connecting to InfluxDB at localhost:8086 (SSL: False, UDP: False)
INFO:root:Creating InfluxDB database if not exists: collectd
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:root:Listening for messages on Kafka topic collectd...
INFO:root:Connecting to Kafka with the following settings:
 {'default.topic.config': {'auto.offset.reset': 'largest'}, 'bootstrap.servers': 'localhost:9092', 'offset.store.method': 'broker', 'group.id': 'my_group'}...
INFO:root:collectd [0] reached end at offset 18683 with key None
INFO:root:collectd [0] reached end at offset 18706 with key None
INFO:root:collectd [0] reached end at offset 18729 with key None
...

With InfluxDB, I can see the database "collectd" created when I use "show databased", however, when I "use collectd" and "show measurements" in influx, nothing appears.

However, if I consume kafka directly, the outputs looks all right:

[root@master kafka_2.11-1.1.0]# bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic collectd
[2018-07-26 17:08:57,060] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-19358 with old generation 0 (__consumer_offsets-27) (kafka.coordinator.group.GroupCoordinator)
[2018-07-26 17:08:57,061] INFO [GroupCoordinator 0]: Stabilized group console-consumer-19358 generation 1 (__consumer_offsets-27) (kafka.coordinator.group.GroupCoordinator)
[2018-07-26 17:08:57,065] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-19358 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-07-26 17:08:57,066] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-27. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[{"values":[6.69987148753071],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"user"}]
[{"values":[2.09994854710406],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"system"}]
[{"values":[8.6997867683244],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"1","type":"cpu","type_instance":"user"}]
[{"values":[0.299992589351314],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"1","type":"cpu","type_instance":"wait"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"nice"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"1","type":"cpu","type_instance":"nice"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"interrupt"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"wait"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"1","type":"cpu","type_instance":"interrupt"}]
[{"values":[0.0999975409963425],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"softirq"}]
[{"values":[0.09999754230013],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"1","type":"cpu","type_instance":"softirq"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"0","type":"cpu","type_instance":"steal"}]
[{"values":[0],"dstypes":["derive"],"dsnames":["value"],"time":1532596144.384,"interval":10.000,"host":"master","plugin":"cpu","plugin_instance":"1","type":"cpu","type_instance":"steal"}]

So I don't know what's going on with writing to InfluxDB. 

Thanks a lot for your help!

Shawn

**Comment by mre** [comment]
Looks like you're using the wrong encoder.
The `collectd_graphite_encoder` is for graphite metrics while the `collectd_json_encoder` is for collectd's JSON format, which is likely what you want. 😉

**Comment by ShawnTheCoder** [comment]
Yes, now it works. 
Thanks! Nice project!

**Comment by mre** [comment]
👍
