### ISSUE TITLE
Installation with pip3

### ISSUE THREAD

**Issue by ShawnTheCoder** [mre/kafka-influxdb#71]
Hi,

I installed kafka-influxdb within my own VMs with python2 successfully. But then, when I try to install in another environment, I directly downloaded the master branch, unzip, and try to run "pip3 install kafka-influxdb", it tells: 

`[root@dhcp-10-173-66-167 kafka-influxdb-master]# pip3 install kafka_influxdb
Collecting kafka_influxdb
  Could not find a version that satisfies the requirement kafka_influxdb (from versions: )
No matching distribution found for kafka_influxdb`

I checked with my pip3 version:
`[root@dhcp-10-173-66-167 kafka_influxdb]# pip3 install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages
You have mail in /var/spool/mail/root
[root@dhcp-10-173-66-167 kafka_influxdb]# pip3 -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)`

And I'm running on CentOS Linux release 7.4.1708 and Linux 3.10.0-693.11.6.el7.x86_64.

Can you help me out of this? 
Thanks in advance!

Shawn.

**Comment by mre** [comment]
Try the full path to the archive, e.g.:

```
pip install /path/to/kafka-influxdb-0.9.0.tar.gz
```

**Comment by mre** [comment]
did it work?

**Comment by ShawnTheCoder** [comment]
Do you mean like this? Seems like I've moved a step forward and with a problem with certifi install...
Sorry I'm not quite familiar with pip, and thanks again :-)
`[root@dhcp-10-173-66-167 kafka-influxdb-master]# pip3 install /usr/share/kafka-influxdb-master/`
`Processing /usr/share/kafka-influxdb-master`
`Collecting certifi (from kafka-influxdb==0.9.3)`
`  Could not find a version that satisfies the requirement certifi (from kafka-influxdb==0.9.3) (from versions: )`
`No matching distribution found for certifi (from kafka-influxdb==0.9.3)`
`[root@dhcp-10-173-66-167 kafka-influxdb-master]# pip3 install certifi`
`Collecting certifi`
 ` Could not find a version that satisfies the requirement certifi (from versions: )`
`No matching distribution found for certifi`
`[root@dhcp-10-173-66-167 kafka-influxdb-master]# pip3 install certifi==2018.1.18`
`Collecting certifi==2018.1.18`
`  Could not find a version that satisfies the requirement certifi==2018.1.18 (from versions: )`
`No matching distribution found for certifi==2018.1.18`

**Comment by ShawnTheCoder** [comment]
I'm trying to download first and install certifi 2018.1.18 from PyPI to my environment, just bear me some time.

**Comment by mre** [comment]
Yup, I can see some progress. 🤠
Looks like you're doing the installation on this server entirely offline, so all packages have to be available from your local machine.


On a machine with internet:

```
mkdir kafka_influxdb
cd kafka_influxdb
pip3 download kafka_influxdb
```

This will create a folder that you can zip and copy to the server.
There, you should be able to unzip it and install again:

```
pip3 install --no-index --find-links /path/to/kafka_influxdb/ kafka_influxdb
```

I haven't tested that, though but it should roughly be what you need to do.
Reference: https://stackoverflow.com/a/14447068/270334

**Comment by ShawnTheCoder** [comment]
Hi, 

We've figured out the pip problem with network proxy. Now I'm able to use pip install kafka_influxdb.
Yeah!

Thanks for your help.
