### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by brunowego** [mre/kafka-influxdb#73]
This package can use authentication by kerberos?

Thanks for your answers!

**Comment by mre** [comment]
Hey @brunowego,

not out of the box.



What would have to be done is the following:

- [ ] Add the new config options for kerberos to the loader [here](https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/config/loader.py#L107).
- [ ] Add the new options to the [default-config](https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/config/default_config.py#L9) and make them `None` by default.
- [ ] Update the [config-example.yml](https://github.com/mre/kafka-influxdb/blob/master/config_example.yaml)
- [ ] Update [reader](https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/reader/reader.py), [confluent](https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/reader/confluent.py), [kafka_python](https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/reader/kafka_python.py) to use those new options if they were set. You can find out more about this in the docs of the projects, [kafka_python here](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html) and [confluent here](https://github.com/confluentinc/confluent-kafka-python/tree/34baea620f063cb96fc32b5a562170f19a19228e#install).
- [ ] Extra points for updating the `README.md` by mentioning how to enable Kerberos support.

Not sure if you have time for it, but just wanted to make sure to document the steps somewhere.

**Comment by mre** [comment]
Alternatively, we could change the entire config handling to pass all options to the Kafka libraries directly, but that would be a bigger change.

**Comment by mre** [comment]
Due to limited time, I won't be able to work on this feature.
Therefore I'm closing this. If anyone wants to tackle it, let me know and we can reopen.
If anyone is looking for a solution, your time might be more wisely spent following [this issue on vector](https://github.com/timberio/vector/issues/1326), which is a superior tool in any regard. 😊
