### ISSUE TITLE
python3 compatibility of echo_encoder

### ISSUE THREAD

**Issue by micpez** [mre/kafka-influxdb#74]
Using  "kafka_influxdb.encoder.echo_encoder" with python3 gives the following error:
WARNING:root:Cannot write data points: sequence item 0: expected str instance, bytes found
Decoding msg solves the issue.

**Comment by mre** [comment]
Sorry about that.
Can you try to remove this line and try again?: https://github.com/mre/kafka-influxdb/blob/master/kafka_influxdb/encoder/echo_encoder.py#L11

**Comment by micpez** [comment]
Same result. But isn't it just a comment? Or did I get the wrong line?
I think it should be msg.decode().

**Comment by mre** [comment]
> Same result. But isn't it just a comment? Or did I get the wrong line?
Nope, it was the correct line. Thought it was related to the type hint. My bad.

>  I think it should be msg.decode().
Yeah that's more like it. Created a PR for that.
