### ISSUE TITLE
Boolean Properties Changed To Strings

### ISSUE THREAD

**Issue by nhproject** [mre/kafka-influxdb#8]
<img width="190" alt="screen shot 2015-10-20 at 17 02 11" src="https://cloud.githubusercontent.com/assets/15214994/10609695/888bc12e-774d-11e5-9e10-62912a543dfd.png">

Hi,

When I'm trying to run kafka-influxdb without config.yaml file and use variables, I have a problem with passing boolean variables.
I'm working with SSL, so I want to pass: --influxdb_use_ssl=True, but then I see in the log that this parameter is received as 'True' and not as it should be (True). Relevant screenshot is attached.
It causes a trouble working with HTTPS and it tries to connect to HTTP while I'm interested connecting to HTTPS.

If I'm working with config.yaml, all works great.

For now, I just changed the default config of this property to True and it works OK.

Thanks,

Nitz

**Comment by mre** [comment]
Thanks for the report. Will have a look as soon as possible.

**Comment by mre** [comment]
Should be fixed in master now.
