### ISSUE TITLE
Values encoded as Strings into Influxdb 0.9x

### ISSUE THREAD

**Issue by borick** [mre/kafka-influxdb#9]
on my setup using centos 6, the Graphite encoder is encoding all values as "strings" into influxdb

I have temporarily edit collectd_graphite_encoder.py as a workaround, comment out the lines which add the "":

        def escape_value(self, value):
            value = self.escape_measurement(value)
            # if isinstance(value, text_type):
            #    return "\"{}\"".format(value.replace(
            #                "\"", "\\\""
            #    ))
            # else:
            return str(value)

**Comment by mre** [comment]
Should be fixed with 4d4b62f
If you want to test it you can clone from master.

Thanks @borick
